set_property PACKAGE_PIN N17 [get_ports {main_clk}]
set_property PACKAGE_PIN D17 [get_ports {reset_n}]
#
set_property PACKAGE_PIN G18 [get_ports {spi_cs_pcm9211_n}]
set_property PACKAGE_PIN F18 [get_ports {spi_cs_pcm1792_n}]
set_property PACKAGE_PIN E18 [get_ports {spi_cs0_n}]
set_property PACKAGE_PIN E19 [get_ports {spi_cs1_n}]
set_property PACKAGE_PIN H19 [get_ports {spi_clk}]
set_property PACKAGE_PIN G19 [get_ports {spi_mosi}]
set_property PACKAGE_PIN H17 [get_ports {spi_miso}]
#
set_property PACKAGE_PIN J19 [get_ports {pcm9211_int0}]
set_property PACKAGE_PIN J17 [get_ports {pcm9211_int1}]
#
set_property PACKAGE_PIN G17 [get_ports {pcm9211_clk}]
set_property PACKAGE_PIN J18 [get_ports {pcm9211_i2s_sclk}]
set_property PACKAGE_PIN L18 [get_ports {pcm9211_i2s_bclk}]
set_property PACKAGE_PIN K18 [get_ports {pcm9211_i2s_lrclk}]
set_property PACKAGE_PIN N18 [get_ports {pcm9211_i2s_d}]
set_property PACKAGE_PIN P17 [get_ports {pcm9211_i2s_clk_out}]
#
set_property PACKAGE_PIN N19 [get_ports {pcm9211_mpio0}]
set_property PACKAGE_PIN P19 [get_ports {pcm9211_mpio1}]
set_property PACKAGE_PIN R19 [get_ports {pcm9211_mpioA[0]}]
set_property PACKAGE_PIN M18 [get_ports {pcm9211_mpioA[1]}]
set_property PACKAGE_PIN M19 [get_ports {pcm9211_mpioA[2]}]
set_property PACKAGE_PIN L17 [get_ports {pcm9211_mpioA[3]}]
set_property PACKAGE_PIN R18 [get_ports {pcm9211_mpioB[0]}]
set_property PACKAGE_PIN U19 [get_ports {pcm9211_mpioB[1]}]
set_property PACKAGE_PIN V19 [get_ports {pcm9211_mpioB[2]}]
set_property PACKAGE_PIN W18 [get_ports {pcm9211_mpioB[3]}]
set_property PACKAGE_PIN T17 [get_ports {pcm9211_mpioC[0]}]
set_property PACKAGE_PIN T18 [get_ports {pcm9211_mpioC[1]}]
set_property PACKAGE_PIN U17 [get_ports {pcm9211_mpioC[2]}]
set_property PACKAGE_PIN U18 [get_ports {pcm9211_mpioC[3]}]
#
set_property PACKAGE_PIN U14 [get_ports {dac_rst}]
set_property PACKAGE_PIN V14 [get_ports {dac_sclk}]
set_property PACKAGE_PIN V13 [get_ports {dac_bclk}]
set_property PACKAGE_PIN U16 [get_ports {dac_data}]
set_property PACKAGE_PIN U15 [get_ports {dac_lrclk}]
set_property PACKAGE_PIN W14 [get_ports {dac_zero_r}]
set_property PACKAGE_PIN W13 [get_ports {dac_zero_l}]
#
set_property PACKAGE_PIN U7  [get_ports {spdif_out}]
#
set_property PACKAGE_PIN W15 [get_ports {sram_spi_cs}]
set_property PACKAGE_PIN V15 [get_ports {sram_spi_clk}]
set_property PACKAGE_PIN W17 [get_ports {sram_spi_sio[0]}]
set_property PACKAGE_PIN W16 [get_ports {sram_spi_sio[1]}]
set_property PACKAGE_PIN V17 [get_ports {sram_spi_sio[2]}]
set_property PACKAGE_PIN V16 [get_ports {sram_spi_sio[3]}]
#
set_property PACKAGE_PIN W19 [get_ports {security}]
#
set_property PACKAGE_PIN J2 [get_ports {led[3]}]
set_property PACKAGE_PIN H2 [get_ports {led[2]}]
set_property PACKAGE_PIN G2 [get_ports {led[1]}]
set_property PACKAGE_PIN G3 [get_ports {led[0]}]
#
set_property PACKAGE_PIN P3 [get_ports {step_drv[0]}]
set_property PACKAGE_PIN N3 [get_ports {step_drv[1]}]
set_property PACKAGE_PIN N1 [get_ports {step_drv[2]}]
set_property PACKAGE_PIN N2 [get_ports {step_drv[3]}]
#
set_property PACKAGE_PIN H1 [get_ports {rPi4}]
set_property PACKAGE_PIN J1 [get_ports {rPi16}]
set_property PACKAGE_PIN K2 [get_ports {rPi17}]
set_property PACKAGE_PIN L2 [get_ports {rPi20}]
set_property PACKAGE_PIN J3 [get_ports {rPix[22]}]
set_property PACKAGE_PIN K3 [get_ports {rPix[23]}]
set_property PACKAGE_PIN L3 [get_ports {rPix[24]}]
set_property PACKAGE_PIN M3 [get_ports {rPix[25]}]
set_property PACKAGE_PIN M2 [get_ports {rPix[26]}]
set_property PACKAGE_PIN M1 [get_ports {rPix[27]}]
#
set_property PACKAGE_PIN A14 [get_ports {aux[0]}]
set_property PACKAGE_PIN C15 [get_ports {aux[1]}]
set_property PACKAGE_PIN B15 [get_ports {aux[2]}]
set_property PACKAGE_PIN A16 [get_ports {aux[3]}]
set_property PACKAGE_PIN A17 [get_ports {aux[4]}]
set_property PACKAGE_PIN C16 [get_ports {aux[5]}]
set_property PACKAGE_PIN B16 [get_ports {aux[6]}]
set_property PACKAGE_PIN C17 [get_ports {aux[7]}]
set_property PACKAGE_PIN B17 [get_ports {aux[8]}]
set_property PACKAGE_PIN B18 [get_ports {aux[9]}]
#
set_property PACKAGE_PIN R2 [get_ports {test[0]}]
set_property PACKAGE_PIN T2 [get_ports {test[1]}]
set_property PACKAGE_PIN R3 [get_ports {test[2]}]
set_property PACKAGE_PIN T3 [get_ports {test[3]}]
set_property PACKAGE_PIN T1 [get_ports {test[4]}]
set_property PACKAGE_PIN U1 [get_ports {test[5]}]
set_property PACKAGE_PIN V2 [get_ports {test[6]}]
set_property PACKAGE_PIN W2 [get_ports {test[7]}]
set_property PACKAGE_PIN V3 [get_ports {test[8]}]
set_property PACKAGE_PIN U3 [get_ports {test[9]}]
set_property PACKAGE_PIN U2 [get_ports {test[10]}]
set_property PACKAGE_PIN U4 [get_ports {test[11]}]
set_property PACKAGE_PIN V4 [get_ports {test[12]}]
set_property PACKAGE_PIN W5 [get_ports {test[13]}]
set_property PACKAGE_PIN W4 [get_ports {test[14]}]
set_property PACKAGE_PIN W7 [get_ports {test[15]}]
set_property PACKAGE_PIN W6 [get_ports {test[16]}]
set_property PACKAGE_PIN U8 [get_ports {test[17]}]
#
##############################################
#
set_property IOSTANDARD LVCMOS33 [get_ports {main_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset_n}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {spi_cs_pcm9211_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_cs_pcm1792_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_cs0_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_cs1_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_mosi}]
set_property IOSTANDARD LVCMOS33 [get_ports {spi_miso}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_int0}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_int1}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_i2s_sclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_i2s_bclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_i2s_lrclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_i2s_d}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_i2s_clk_out}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpio0}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpio1}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioC[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioC[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pcm9211_mpioC[3]}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {dac_rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_bclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_lrclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_zero_r}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_zero_l}]
#
set_property IOSTANDARD LVCMOS18 [get_ports {spdif_out}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {sram_spi_cs}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_spi_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_spi_sio[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_spi_sio[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_spi_sio[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sram_spi_sio[3]}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {security}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {step_drv[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {step_drv[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {step_drv[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {step_drv[3]}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {rPi4}]
set_property IOSTANDARD LVCMOS33 [get_ports {rPi16}]
set_property IOSTANDARD LVCMOS33 [get_ports {rPi17}]
set_property IOSTANDARD LVCMOS33 [get_ports {rPi20}]
set_property IOSTANDARD LVCMOS33 [get_ports {rPix[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rPix[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rPix[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rPix[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rPix[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rPix[27]}]
#
set_property IOSTANDARD LVCMOS33 [get_ports {aux[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aux[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aux[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aux[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aux[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aux[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aux[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aux[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aux[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {aux[9]}]
#
set_property IOSTANDARD LVCMOS18 [get_ports {test[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {test[17]}]




